### ISSUE TITLE
Dropped Java 8 support in a 3.0.x patch release

### ISSUE THREAD

**Issue by jonatan-ivanov** [eclipse-ee4j/glassfish-hk2#1084] opened 2024-08-09 18:40 UTC
Upgrading from `org.glassfish.hk2:hk2-api:3.0.3` to `3.0.6` causes `UnsupportedClassVersionError`, it seems the Java baseline was elevated from Java 8 to eleven between those patch versions:
```
java.lang.UnsupportedClassVersionError: org/glassfish/hk2/api/ServiceLocatorFactory has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by pzygielo** [comment] 2024-08-09 19:07
- duplicate of #888

**Closed by pzygielo** 2024-08-09 19:07 UTC

**Comment by jonatan-ivanov** [comment] 2024-08-10 22:39
Thank you. Sorry for the dupe, I did not see that issue.
Could you please consider commenting it? It seems rather serious.
