### ISSUE TITLE
3.0.2 tag missing problem

### ISSUE THREAD

**Issue by CChengjie** [eclipse-ee4j/glassfish-hk2#716] opened 2022-08-26 06:47 UTC
We found that version 3.0.2 was released in Maven, but there was no corresponding tag in github. [3.0.1 and 3.0.3 are existent]
1）What is the reason for tag's absence?

- a、This version code has problems, such as the loophole, compatibility and interface issues, etc.
- b、This version has functional problems, such as unreasonable function planning, basic function cannot be used
- c、Forgot to tag
- d、Don't care or is too trouble
- e、others，_

2） To solve this problem, we propose a method that can find the true commit of version to help developers quickly locate the problem code and fix the bug. Here are the possible true commits given by our method. Can you confirm whether or not the actual commits are included, and if not, which ones?

['228631e9149624c02e5561b79bf6a54bebe2c582', '6c5ca9902c8d9e6565594a1152e29207a604e636', '00b7e0058ec4036ec9be3451e41eb952bb3df8bc', '644009720d6714bf272c30e31297629e2773d546']

♥ This question is very important to our research. Thank you for your time!

**Comment by pzygielo** [comment] 2022-08-26 08:14
Duplicate of #553

**Closed by pzygielo** 2022-08-26 08:14 UTC
